### ISSUE TITLE
customize

### ISSUE THREAD

**Issue by martinledoux** [Project-OSRM/osrm-frontend#291]
please i need a help.
can someone help me set my local tile server to the osrm-frontend ?

**Comment by bryanibit** [comment]
I have a similar demand: I want to display the routing result of **osrm-backend** and show my own map (consisting of raster .tiff and vector .osm). Both of them are located in local directory. How to achieve that with **osrm-frontend**? Thank you for reply.

**Comment by adhamenaya** [comment]
@martinledoux @bryanibit I think it is too late to answer this question, but it is good to share it for future askers. We need to change in the file `src/leaflet_options.js` in the `module.exports` we need to define our routing server path in the following code:
```
  services: [{
    label: 'Car (fastest)',
    path: 'https://router.project-osrm.org/route/v1'
  }],
```

**Comment by morganherlocker** [comment]
As @adhamenaya notes, the current docs explain how to configure osrm-frontend with a local tile store, including an example pointing to localhost:

https://github.com/Project-OSRM/osrm-frontend#changing-backends

**Comment by rachha** [comment]
Hey @bryanibit, If you're using raster data, it means you're changing the weight of the segment. So you might be displaying along with distance and duration can you help me  #302
