### ISSUE TITLE
How to change polyline color by mode?

### ISSUE THREAD

**Issue by alireaza** [Project-OSRM/osrm-frontend#293]

**Comment by morganherlocker** [comment]
Line options that are passed to leaflet-routing-machine (the frontend lib used for drawing and style route lines) lives [here](https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/src/lrm_options.js#L9-L12). OSRM only supports one mode at a time, so assuming you made the changes to support 2+ backends with a server powering each mode, you would create one leaflet-routing-machine instance per backend with custom styles defined [here](https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/src/index.js#L138). Hope that answers your question. 🙇
