### ISSUE TITLE
Adding way attributes on debug map

### ISSUE THREAD

**Issue by alain-andre** [Project-OSRM/osrm-frontend#294]
I would like to be able to add some way attributes on debug maps, I cannot figure how to do, any idea of how I could ?

**Comment by danpat** [comment]
@alain-andre OSRM doesn't store all the way data.  You would need to generate your own map tiles from the OSM data, serve them up separately, and add them as a separate layer on the map, using something like https://openmaptiles.org/osm2vectortiles/

The tiles served up by OSRM can only expose the data that OSRM has stored in its data structures, which is limited to only the minimum needed for route calculation and guidance generation.

**Comment by alain-andre** [comment]
Exactly what I need. Thanks.
