### ISSUE TITLE
want to show weight field value along with distance and duration

### ISSUE THREAD

**Issue by rachha** [Project-OSRM/osrm-frontend#302]
I made some changes in osrm-backend, so weight and duration fields are not going to be the same. Therefore I want to show weight along with duration and distance. Which part of the code I need to change.

Thanks
![Screenshot from 2019-04-29 19-06-45](https://user-images.githubusercontent.com/16594628/56900250-ff369180-6ab2-11e9-96a6-319af747ffe4.png)
![155654548663274631](https://user-images.githubusercontent.com/16594628/56900839-6ef94c00-6ab4-11e9-93bd-d534e6e23122.png)

**Comment by yuryleb** [comment]
IMHO you should insert new column to table at https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/src/itinerary_builder.js#L101 and fill it before distance (so as it could be zero and skipped) before https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/src/itinerary_builder.js#L138

**Comment by rachha** [comment]
Thanks @yuryleb, but the one you suggested will be useful when I want to show details of every subpath(step), but I'm not interested in that. I suppose to show the weight of an overall path.

![Screenshot from 2019-04-30 03-44-50](https://user-images.githubusercontent.com/16594628/56930514-8b1fdc00-6afa-11e9-93af-366834dbfde2.png)

**Comment by rachha** [comment]
any help @yuryleb @perliedman  thanks.
