### ISSUE TITLE
Open in JSOM: Localhost link on Production

### ISSUE THREAD

**Issue by Sean12697** [Project-OSRM/osrm-frontend#315]
https://github.com/Project-OSRM/osrm-frontend/blob/7466ebadef54a45d01a8e64944d757bc62646284/src/tools.js#L79

**Comment by danpat** [comment]
This is not a bug - JOSM is a map editing tool that runs on your local desktop - the purpose of this link is to take you from a location on the OSRM frontend, into the same location in your desktop JOSM instance.
