### ISSUE TITLE
Leaflet options are not valid

### ISSUE THREAD

**Issue by madmath03** [Project-OSRM/osrm-frontend#329]
MapBox API layers are 410 (Gone) and should be removed from leaflet options:
https://github.com/Project-OSRM/osrm-frontend/blob/7466ebadef54a45d01a8e64944d757bc62646284/src/leaflet_options.js#L5-L21

Also, would be nice to have hiking and biking options instead of geofabrik small components which is not available either.

**Comment by mjjbell** [comment]
Fixed by #331

**Comment by rooton** [comment]
Really dont know what was fixed. But it still show 

`GET https://api.mapbox.com/v4/mapbox.streets/13/2344/3132@2x.png?access_token=pk.eyJ1IjoibXNsZWUiLCJhIjoiclpiTWV5SSJ9.P_h8r37vD8jpIH1A6i1VRg 410 (Gone)`
