### ISSUE TITLE
How to install backend without using docker.

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-frontend#334]
Hey, I am facing problem in installation of OSRM- backend without using docker. Can anyone help me how to do that and connect it with front-end of OSRM.

**Comment by danpat** [comment]
Please see the Wiki for instructions on building OSRM from source if you can't use the supplied Docker containers.

You can read the `Dockerfile` for step-by-step commands to compile OSRM on your own system.

**Comment by ghost** [comment]
> e the Wiki for instructions on building OSRM fro

Thanks for reply.Can you suggest me any website which shows how to install osrm backend without docker containers.

**Comment by danpat** [comment]
@m33meet Read the instructions here: https://github.com/Project-OSRM/osrm-backend/wiki - Section 1 "Installation and usage".
