### ISSUE TITLE
Where is the profile-selector control?

### ISSUE THREAD

**Issue by tumluliu** [Project-OSRM/osrm-frontend#349]
Hi there,

Thank you for creating such a nice project! It seems that the frontend hosted at https://map.project-osrm.org/ is slightly different from the latest version in the repo. From the demo website, the profile selector is available and working fine:

<img width="202" alt="osrm-fe-with-modes" src="https://user-images.githubusercontent.com/1563792/163391337-1ffee5d1-712b-4c24-bd29-ef8a23cc80fe.PNG">

But the one launched from the `gh-pages` branch doesn't have such part:

<img width="201" alt="osrm-FE-no-profile" src="https://user-images.githubusercontent.com/1563792/163391097-f3a8fad4-e400-427e-96bb-e63287e65ca2.PNG">

Is the profile selecting function available from any of the branch in the repo? Thanks!

**Comment by datendelphin** [comment]
Yes that is a hack for the fossgis routing server, which is currently acting as the demo server. You find the respective forked repositories on the about page https://map.project-osrm.org/about.html

**Comment by tumluliu** [comment]
oh wow, thank you @datendelphin so much for your quick reply. That's super helpful!
