### ISSUE TITLE
Feature suggestion: Add the OSRM backend tile service layer

### ISSUE THREAD

**Issue by alexanderzatko** [Project-OSRM/osrm-frontend#373]
It would be great if the frontend allowed viewing the [backend tile service](http://project-osrm.org/docs/v5.24.0/api/#tile-service) tiles. Ideally on an overlay layer.

**Comment by jcoupey** [comment]
If you're using `osrm-frontend` on your own instance, this is already available at `/debug`, see https://github.com/Project-OSRM/osrm-frontend#changing-backends.

**Comment by alexanderzatko** [comment]
excellent. Thank you 👍
