### ISSUE TITLE
Unable to view map 

### ISSUE THREAD

**Issue by Shailesh913** [Project-OSRM/osrm-frontend#378]
Hi ,

Need help with respect to UI. I setup the frontend and backend on two dffferent Containers but when accessing the URL I can't see the Map. The UI elements like the start/end markers, zoom controls, and layer switcher are visible, but the actual map area is blank white. This suggests that there might be an issue with loading the map tiles.

Any help highly appreciated as I'm completely new to OSRM and OSM.

Attached screenshot for any reference
![Screenshot from 2024-09-21 15-02-00](https://github.com/user-attachments/assets/b9d84d00-eded-4719-b5e7-e322b405bd90)

**Comment by DavidLucky0** [comment]
Hi! 
I meet the same question. Have you solved this problem?

**Comment by jcoupey** [comment]
You want to pick the OSM tile layer from the selector in the bottom right.

**Comment by mikolyan** [comment]
Sorry, but I don't see the OSM tile layer at the bottom right
![image](https://github.com/user-attachments/assets/61af25e0-f1a2-4a1c-beb7-1827af00ef51)

**Comment by jcoupey** [comment]
Yeah, the selector is on the bottom left...

**Comment by mikolyan** [comment]
Sorry for the stupid question. Do I understand correctly, that maps can only be loaded online? What is the backend for then? To calculate the route? Or can I still make my own offline map server? Thanks in advance for your answers!

**Comment by jcoupey** [comment]
Yes OSRM is in charge of computing the routes. To display the result on a map, you need map tiles that come from somewhere, usually an online third party provider. You could also deploy your own OSM tile server locally, you'll find different options and tutorials for this out there.

**Comment by mikolyan** [comment]
Thank you very much, now it's clear. I'll think about how to deploy my own server with map tiles.
