### ISSUE TITLE
Same OSRM server, two different routes using v1 or v2

### ISSUE THREAD

**Issue by stevage** [Project-OSRM/osrm-frontend#44]
Look at this:

http://cycletour.org/?hl=en&loc=-37.755264,145.347467&loc=-37.753380,145.694833&z=12&center=-37.768544,145.470829

http://cycletour.org/v2/?hl=en&loc=-37.755264,145.347467&loc=-37.753380,145.694833&z=12&center=-37.768544,145.470829

These two front ends both use the same back end (osrm.cycletour.org:5010), yet return very different routes. Any idea why?

I see some slight differences in the generated URLs. v1 has this:

```
z:12
output:json
jsonp:OSRM.JSONP.callbacks.route
loc:-37.755218,145.347633
loc:-37.753236,145.697698
instructions:true
```

v2 has this

```
instructions:true
alt:true
loc:-37.755302,145.347839
loc:-37.75256,145.694351
jsonp:_l_routing_machine_0
```

Is it the `alt` which is causing the difference? I don't have an easy way of testing.

**Comment by TheMarex** [comment]
Hm, interesting. These are the requests send to the back-end, right? Probably there is a subtle difference in how the interplay of geocoder + coordinates works.
Will check this out when I have some spare time.

**Comment by perliedman** [comment]
@stevage are you sure osrm.cycletour.org and cycletour.org are actually the same OSRM instance? Your v1 uses the former, v2 uses the later. I get different results when I perform the same OSRM query to those two hosts, so I would guess it's actually two different OSRM instances that are set up differently.

**Comment by stevage** [comment]
*facepalm*

Thanks - indeed, osrm.cycletour.org and cycletour.org are running different profiles. I didn't see the difference in the host name, no matter how closely I stared at it (or for how long...)
